apiVersion: v1
kind: Pod
metadata:
 name: catch-sleep
 labels:
   app: catch-sleep
spec:
 containers:
 - name: catch-sleep
   image: jam2in/sigcatch_example:0.1.0
   command: ["/sigcatch_example/catch"]
   lifecycle:
     preStop:
       exec:
         command: ["sleep 30"]
 terminationGracePeriodSeconds: 20
