apiVersion: v1
kind: Pod
metadata:
 name: catch-sleep
 labels:
   app: catch-sleep
spec:
 containers:
     #imagePullPolicy: Always
 - name: catch-sleep
   image: jam2in/sigcatch_example:latest
   command: ["/sigcatch_example/catch"]
   lifecycle:
     preStop:
       exec:
         command: ['/bin/sh', '-c', 'sleep 50']
 terminationGracePeriodSeconds: 10
