apiVersion: v1
kind: Pod
metadata:
 name: catch-sleep
 labels:
   app: catch-sleep
spec:
 containers:
     #imagePullPolicy: Always
 - name: catch-sleep
   image: jam2in/sigcatch_example:latest
   command: ["malloc"]
   lifecycle:
     preStop:
       exec:
         command: ['/bin/sh', '-c', 'sleep 10000']
 terminationGracePeriodSeconds: 1000000
