apiVersion: v1
kind: Pod
metadata:
 name: catch
 labels:
   app: catch
spec:
 containers:
 - name: catch
   image: jam2in/sigcatch_example:latest
   command: ["/sigcatch_example/catch"]
   #imagePullPolicy: Always
 terminationGracePeriodSeconds: 20
