apiVersion: v1
kind: Pod
metadata:
 name: malloc
 labels:
   app: malloc
spec:
 containers:
     #imagePullPolicy: Always
 - name: malloc
   image: jam2in/eviction_example:latest
   #1.5Gb
   command: ['malloc', '1700']
   lifecycle:
     preStop:
       exec:
         command: ['/bin/sh', '-c', 'sleep 600']
 terminationGracePeriodSeconds: 1000
