apiVersion: v1
kind: Pod
metadata:
 name: malloc
 labels:
   app: malloc
spec:
 containers:
     #imagePullPolicy: Always
 - name: malloc
   image: jam2in/eviction_example:latest
   #1.5Gb
   command: ['/sigcatch_example/malloc', '1700']
   #command: ['/bin/bash', '-c', 'sleep 500000']
   lifecycle:
     preStop:
       exec:
         command: ['/bin/sh', '-c', 'sleep 50']
 terminationGracePeriodSeconds: 10
